//! Groth16 verifier for the tidex6 hidden-amount join-split circuit (TransferCircuit, four public inputs), on Stylus.
//!
//! Same verifying key and same `verifyProof` ABI as
//! `contracts/src/Tidex6HiddenTransferVerifier.sol`. The pairing arithmetic lives in
//! `tidex6_stylus_common::groth16`, shared with the other verifiers; this
//! crate is the key (`vk.rs`, generated by `export_evm_verifiers`) and the
//! entry point.

#![cfg_attr(not(any(test, feature = "export-abi")), no_std)]
extern crate alloc;

#[allow(unused_imports)]
use alloc::vec;
#[allow(unused_imports)]
use alloc::vec::Vec;

mod vk;

use alloy_primitives::{Address, U256};
use stylus_sdk::call::RawCall;
use stylus_sdk::prelude::*;

use tidex6_stylus_common::groth16;

#[storage]
#[entrypoint]
pub struct Tidex6HiddenTransferVerifier {}

#[public]
impl Tidex6HiddenTransferVerifier {
    /// Verify a proof against the embedded key. Rejects any public input that
    /// is not a scalar-field element before touching a precompile.
    #[selector(name = "verifyProof")]
    pub fn verify_proof(
        &self,
        pa: [U256; 2],
        pb: [[U256; 2]; 2],
        pc: [U256; 2],
        pub_signals: [U256; vk::NR_PUBLIC_INPUTS],
    ) -> bool {
        let key = groth16::VerifyingKey {
            alpha: &vk::ALPHA,
            beta: &vk::BETA,
            gamma: &vk::GAMMA,
            delta: &vk::DELTA,
            ic: &vk::IC,
        };
        let precompile = |target: Address, input: &[u8]| -> Option<Vec<u8>> {
            unsafe { RawCall::new_static(self.vm()).call(target, input).ok() }
        };
        groth16::verify(&key, precompile, pa, pb, pc, &pub_signals)
    }
}
