// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_token_verifiers.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract. The confidential-token       #
// # circuits join the ceremony in the next cycle; until then #
// # this key is a development key by construction.           #
// ############################################################

/// @title Baby Jubjub constants, generated from the circuit crate
/// @notice The curve the confidential-token ciphertexts live on:
///         a twisted Edwards curve whose coordinates are elements of
///         the BN254 scalar field. That is the whole reason it is
///         used — inside a Groth16 circuit over BN254 its arithmetic
///         is native, so a point addition costs units of constraints
///         instead of hundreds of thousands.
///
/// @dev Generated by `export_token_verifiers`. The contract and the
///      circuits must agree on every digit here: a wrong `H` still
///      compiles and still verifies, and produces balances whose
///      owner cannot decrypt them.
library BabyJubjubConstants {
    /// Base field of the curve = scalar field of BN254.
    uint256 internal constant P =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// Order of the prime-order subgroup: valid secret scalars are below it.
    uint256 internal constant L =
        2736030358979909402780800718157159386076813972158567259200215660948447373041;

    /// Curve coefficient `a` of `a*x^2 + y^2 = 1 + d*x^2*y^2`.
    uint256 internal constant A = 1;

    /// Curve coefficient `d`.
    uint256 internal constant D = 9706598848417545097372247223557719406784115219466060233080913168975159366771;

    /// Generator `G`: amounts are committed as `m*G`.
    uint256 internal constant GX =
        19698561148652590122159747500897617769866003486955115824547446575314762165298;
    uint256 internal constant GY =
        19298250018296453272277890825869354524455968081175474282777126169995084727839;

    /// Second generator `H`, hash-derived: blinding is `r*H`, and a
    /// public key is `s^-1 * H`.
    uint256 internal constant HX =
        16465905457043935148917040939103774432138530608084226140289605407230083015565;
    uint256 internal constant HY =
        11338370919383712937350239847103076912175434237534229070573696180793149629513;
}
