// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_token_verifiers.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract. The confidential-token       #
// # circuits join the ceremony in the next cycle; until then #
// # this key is a development key by construction.           #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 confidential-token transfer circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 18
contract Tidex6TokenTransferVerifier {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 5579279763765901853158760881749785391086222456936523776260516540365599773776;
    uint256 constant alphay = 5441494127181855949694969750880090064967098234091355711372301767189825865752;

    uint256 constant betax1 = 8921495245730693922580867115712773780898129172790039588335988540838210304471;
    uint256 constant betax2 = 4329442438519151095068614310735821740095619045927537313374012740012054530893;
    uint256 constant betay1 = 19692330268906956286044568421435402833970635136851887040102012760167834809287;
    uint256 constant betay2 = 17876476682313413283322720975421317804648637936450454375012325963851186839043;

    uint256 constant gammax1 = 19821674628341264807193390985993689451821105736412376089380323339763035703376;
    uint256 constant gammax2 = 6309732101647849640247862402053211923526537895492322851671613242471418137131;
    uint256 constant gammay1 = 7503120594414210238966507430617252133262401880413145508769376760048896724970;
    uint256 constant gammay2 = 8432283793750919601878540587012265231384513259386015180649382049872726911579;

    uint256 constant deltax1 = 2671228144654920755724007729604236219455569637631652926863159771335035776658;
    uint256 constant deltax2 = 8370176673091599187943509923745413301959133992662410626616852775394970222143;
    uint256 constant deltay1 = 11247221176653602428093151154432833661539515122170895124942482755758494733058;
    uint256 constant deltay2 = 13652973118612031466986621252608807798782287850338124047428809538898521923701;

    uint256 constant IC0x = 5281329943265344044329027087070259032844995887831663953739940903227563815468;
    uint256 constant IC0y = 5701022073434698641493215058990447882770850508746614867321258980082438050395;

    uint256 constant IC1x = 5696079138799682738721477175079618485290417955445220078558699638360166641241;
    uint256 constant IC1y = 10205699715558558387023758047436112322124828311553876623876024801725028289559;

    uint256 constant IC2x = 5939001682827529157853541878336657495661309832053594449163790818503790821193;
    uint256 constant IC2y = 2985837489636102439298355429048572574689441732660305346755332511627437041861;

    uint256 constant IC3x = 20984958589220841824629691519906243007257346964700080559558887546944053919957;
    uint256 constant IC3y = 10587484274739733638902587310921971016417244391029743142937586029522295268164;

    uint256 constant IC4x = 10335844311005409267480707798046485332323666997588773219925935680429806340072;
    uint256 constant IC4y = 5428921420721197006776735856376037104488639167988251016942163925465478749033;

    uint256 constant IC5x = 9190461570124003680093908214848733594085097035978104438047346439847851797089;
    uint256 constant IC5y = 984295894760780799353928250218618410582569714079372570294464186628607733390;

    uint256 constant IC6x = 9078487067488443413841104391602995319921489918511948928639090840780064223252;
    uint256 constant IC6y = 5098874269046242848670925130670575214741230207113264826128164832827644806999;

    uint256 constant IC7x = 15735654625204877115550358858404558320080476224504076998953646820542241736635;
    uint256 constant IC7y = 15369472130230546941916703484487429990081071686122697833292545990086034248432;

    uint256 constant IC8x = 3217483721379226090021154788845749837299353908009483639087880979753938959898;
    uint256 constant IC8y = 1893140731736218436315220594596561788301122944147834842999601672532693814809;

    uint256 constant IC9x = 12275701399198498030830457434664076629095626901369176679964890146642868630178;
    uint256 constant IC9y = 18565177659338343309083257895847366974565912549934357741441085575353412833688;

    uint256 constant IC10x = 12610928644666264519704784693765162031936438222575651830042191986292447061081;
    uint256 constant IC10y = 919656948784027595160467552231882844084373545817949029519268589262452363157;

    uint256 constant IC11x = 21116727395589143423931320856774862372838583343050255193614100098656446900715;
    uint256 constant IC11y = 13877726017553295112115269445058397077867493953181746465770246083902849211761;

    uint256 constant IC12x = 10760480995049445401568765755089669224817591713305779729323719061411062925445;
    uint256 constant IC12y = 21118898892598670860611468099739787174120340298285679641800107336781497953677;

    uint256 constant IC13x = 3423893480013722269302046487564338812825734490913663959009373636260029588693;
    uint256 constant IC13y = 1902837697999303536359754421995476550195873922291575065774205229698744432414;

    uint256 constant IC14x = 1455409786041773530471357630585654705827899174845904203220088801275048807813;
    uint256 constant IC14y = 5274020935766601850047836954835457531814205447311326898754765233607999401980;

    uint256 constant IC15x = 16321571334330847638149461224594423495179275918104067758424415648693940012951;
    uint256 constant IC15y = 9554747484582225798176210998126727861177641529108232474629785812228000231236;

    uint256 constant IC16x = 14566860640702352223832764393088855008747940135722415089876620591568951463424;
    uint256 constant IC16y = 12498462847972979410643135832876073168949022056779402898655289659582561850706;

    uint256 constant IC17x = 3724503788649040811887933718476163893588727791247503952142892941076474507353;
    uint256 constant IC17y = 12631087179240989275194387684725379741481499976663458938747134918946336210563;

    uint256 constant IC18x = 20471433690443147018404374215812086068796592301978149888648290316813366823010;
    uint256 constant IC18y = 8484088725586725361000900503643872173478241842165888713444603617367993653399;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 18 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[18] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1MulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                g1MulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                g1MulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                g1MulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))
                g1MulAccC(_pVk, IC9x, IC9y, calldataload(add(pubSignals, 256)))
                g1MulAccC(_pVk, IC10x, IC10y, calldataload(add(pubSignals, 288)))
                g1MulAccC(_pVk, IC11x, IC11y, calldataload(add(pubSignals, 320)))
                g1MulAccC(_pVk, IC12x, IC12y, calldataload(add(pubSignals, 352)))
                g1MulAccC(_pVk, IC13x, IC13y, calldataload(add(pubSignals, 384)))
                g1MulAccC(_pVk, IC14x, IC14y, calldataload(add(pubSignals, 416)))
                g1MulAccC(_pVk, IC15x, IC15y, calldataload(add(pubSignals, 448)))
                g1MulAccC(_pVk, IC16x, IC16y, calldataload(add(pubSignals, 480)))
                g1MulAccC(_pVk, IC17x, IC17y, calldataload(add(pubSignals, 512)))
                g1MulAccC(_pVk, IC18x, IC18y, calldataload(add(pubSignals, 544)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))
            checkField(calldataload(add(_pubSignals, 160)))
            checkField(calldataload(add(_pubSignals, 192)))
            checkField(calldataload(add(_pubSignals, 224)))
            checkField(calldataload(add(_pubSignals, 256)))
            checkField(calldataload(add(_pubSignals, 288)))
            checkField(calldataload(add(_pubSignals, 320)))
            checkField(calldataload(add(_pubSignals, 352)))
            checkField(calldataload(add(_pubSignals, 384)))
            checkField(calldataload(add(_pubSignals, 416)))
            checkField(calldataload(add(_pubSignals, 448)))
            checkField(calldataload(add(_pubSignals, 480)))
            checkField(calldataload(add(_pubSignals, 512)))
            checkField(calldataload(add(_pubSignals, 544)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
