// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_token_verifiers.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract. The confidential-token       #
// # circuits join the ceremony in the next cycle; until then #
// # this key is a development key by construction.           #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 confidential-token deposit-to-pool circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 11
contract Tidex6TokenDepositVerifier {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 15585012536757601693222637881570617644968318313375173210141545288548726025312;
    uint256 constant alphay = 12546036614804377878708713462240998677816142580597890855608465309189690244080;

    uint256 constant betax1 = 3459715188517196913664621056182970989293652722494660046287066805326494584177;
    uint256 constant betax2 = 10575497743397910323681659682586758135113741810553773658939301094539936309288;
    uint256 constant betay1 = 2551636233662038339813978380655366912656459076626709141580529640683692072204;
    uint256 constant betay2 = 9847680550756407421551844958506192652805379139000773906893544849663616211909;

    uint256 constant gammax1 = 9970672120202180152541979248227121059631430433060082795801967078790115457937;
    uint256 constant gammax2 = 15014316287858862804062540443468085623497498305256905509137194950221975851057;
    uint256 constant gammay1 = 18805423038408883452979208162181615097521252418551122791709431622548136525823;
    uint256 constant gammay2 = 18870936509090914421459330188820022947384466855476281721667119865294961901584;

    uint256 constant deltax1 = 844825431511132896238933146015420365912914947567141727131347992326660236133;
    uint256 constant deltax2 = 11973177913770460975593376190938024957494377941579348598727419375581720647103;
    uint256 constant deltay1 = 11024477061065275389767040917866374991096759239962453152993406878634373249221;
    uint256 constant deltay2 = 14079988633930062081016785270536790441297365929818919195463469395216489300112;

    uint256 constant IC0x = 9945651324547385747064953310395554772655630875635770667184904491780828367997;
    uint256 constant IC0y = 13441212516383644746165423528136240134027737382328273643182555118195652364611;

    uint256 constant IC1x = 301479376010506842051588456200771113706659644082371662271998640401698967712;
    uint256 constant IC1y = 5660093275658740862626406650365214835085697229094848087648865822274105002471;

    uint256 constant IC2x = 20214077975687562277482695682176039011812096989247377697110052404698700286906;
    uint256 constant IC2y = 9412194080427409119882390246751342129663991551601084538967770938976752266844;

    uint256 constant IC3x = 6592273517293788740959367863046527609222115455429214911648237088260232576614;
    uint256 constant IC3y = 4128360048563210510255730926273347653994977546986653450180439196470134476487;

    uint256 constant IC4x = 5964688678498858215650751311777836479559316928689962332226697889312591522542;
    uint256 constant IC4y = 14410143926305750125073580667404524458912908642671776230998505439476973311178;

    uint256 constant IC5x = 874524100510046648326955103557109882402511350541417102948352030502563344214;
    uint256 constant IC5y = 5019743353750986323592060784067774234080242748043371040289623193913396556538;

    uint256 constant IC6x = 21514448832027092962293417337879481815149718517605681278683929184036101594153;
    uint256 constant IC6y = 13815485271156797152822153777604452113293104528674905733606229862902860324656;

    uint256 constant IC7x = 21037295358060021316048087533177634225146841346281221062644106820189476549405;
    uint256 constant IC7y = 20413668662773090829610744189310876002762876318602158978787850598662441567472;

    uint256 constant IC8x = 11446733458355730125872388290163093535499524645936158189642808821294651426891;
    uint256 constant IC8y = 10415911897810625776449262555001861136885682816847799586823689685122034921545;

    uint256 constant IC9x = 12965509987689506646767684202222160972377860731396707588231643973594758463558;
    uint256 constant IC9y = 721440560501115099223712979392268218790117712967322371764157420720726704654;

    uint256 constant IC10x = 18065447258446917714931473245420197229716645807720321391823517789279615670872;
    uint256 constant IC10y = 5446840434901654640991326401611136791079280991144640014653462352942214771864;

    uint256 constant IC11x = 17314009670378900825017076511383705901429633480134397704400027290635640249403;
    uint256 constant IC11y = 2533644950947776167560861535176107271353316632271651452325400511712001725700;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 11 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[11] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1MulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                g1MulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                g1MulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                g1MulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))
                g1MulAccC(_pVk, IC9x, IC9y, calldataload(add(pubSignals, 256)))
                g1MulAccC(_pVk, IC10x, IC10y, calldataload(add(pubSignals, 288)))
                g1MulAccC(_pVk, IC11x, IC11y, calldataload(add(pubSignals, 320)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))
            checkField(calldataload(add(_pubSignals, 160)))
            checkField(calldataload(add(_pubSignals, 192)))
            checkField(calldataload(add(_pubSignals, 224)))
            checkField(calldataload(add(_pubSignals, 256)))
            checkField(calldataload(add(_pubSignals, 288)))
            checkField(calldataload(add(_pubSignals, 320)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
