// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_evm_verifiers.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract.                              #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 hidden-amount join-split circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 4
contract Tidex6HiddenTransferVerifier {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 12148994984003143266095050532559878232921425321033081763331623491295368889897;
    uint256 constant alphay = 1516337208687065944577737883828706698631922356658298817326139693409048966542;

    uint256 constant betax1 = 12055898098262324730012521632260074959206684074056143674379616123361359968393;
    uint256 constant betax2 = 3323098371056138736886050381126254685639052279529335667265609977762327160498;
    uint256 constant betay1 = 11182530925335314456301638578072854856474560448762397035401424098966614176925;
    uint256 constant betay2 = 7628175112379097877887824916157077956269677797124507614782364069535255897039;

    uint256 constant gammax1 = 19014267376066449985357830496654359553232210111969358591537734226818815626236;
    uint256 constant gammax2 = 21564962068685355857639640712859760659609863930800254737407079435889526163708;
    uint256 constant gammay1 = 2189246933980685737189303048854131086140457958566339327571662493097573268637;
    uint256 constant gammay2 = 14603231182790227727345352714109705427644009286523276808360950989067285744484;

    uint256 constant deltax1 = 10394727658141518892366473479504147121251943109670263741384278621578412268928;
    uint256 constant deltax2 = 6123050270376805903443864189028969900029286982452626057894196401993911889927;
    uint256 constant deltay1 = 4179148480391231245469744454227229789915815226685353954213255936016655636949;
    uint256 constant deltay2 = 14037720473137961352978493513979305822770936750585729678787282075302590444830;

    uint256 constant IC0x = 21336106759971480611972991678315973947097275757407707043989706604076110648329;
    uint256 constant IC0y = 6487122635823080326898303161522222569351320615472697760093007172854385047387;

    uint256 constant IC1x = 14701016234207160301015025391495937367965238346371948069421550999352830805758;
    uint256 constant IC1y = 19396239276363859395939469223533802296425121308914193964733351311412854468820;

    uint256 constant IC2x = 8487000657288375430504006620993378391790324236806971647374295775936200516394;
    uint256 constant IC2y = 20027325145544754576516077556021276460926751644457548355577276748352752323805;

    uint256 constant IC3x = 20370124315390915758588753286421701493511571527851897094151700976660532319523;
    uint256 constant IC3y = 6501967411624775040850384749013128508874250952012854784037912635275993856523;

    uint256 constant IC4x = 7351676505575896175215718151745584269671511116379529582080095610520340938701;
    uint256 constant IC4y = 13542605218971455654075232044887645236237736297365298841712895679557861942377;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 4 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
