// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_token_verifiers.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract. The confidential-token       #
// # circuits join the ceremony in the next cycle; until then #
// # this key is a development key by construction.           #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 confidential-token public-key validity circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 4
contract Tidex6TokenPubkeyVerifier {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 438116471510737490197824487081034192454026956563767306595695591735043563046;
    uint256 constant alphay = 2187225794179467439361320715913798691994801437292958045234333517410082245682;

    uint256 constant betax1 = 10661825007960239484052670690415914706582994810433639660466913538584345766168;
    uint256 constant betax2 = 4796635196195873875653761327389210877613861039022093646616081578350502428948;
    uint256 constant betay1 = 5710302018543180894308652231058975435526097401960792298951317973618651974972;
    uint256 constant betay2 = 8603655646806086995936610382700739132364237197701783425803904804775049354396;

    uint256 constant gammax1 = 20402949393793347633268221603351024071731537452479630941093437177203349507413;
    uint256 constant gammax2 = 14089067295117945439708295816343549687761402197380341789968550490368199426635;
    uint256 constant gammay1 = 5919296648035049869983830873443544218822495188627352212433857542520864804867;
    uint256 constant gammay2 = 18126808474271897609376741876703873652427933400312268083072192960184377202350;

    uint256 constant deltax1 = 13336108846218530634682917964922162669770977890987866040436633396936201022182;
    uint256 constant deltax2 = 14136223838792659190595402694087727806481610481194733290249394982733184874265;
    uint256 constant deltay1 = 10864777115067762553148331907591701985194201865816545969701094215436697515276;
    uint256 constant deltay2 = 6817090161164484406492694016368556299424224441797312116364309305081510557965;

    uint256 constant IC0x = 12335876343217589129253180183910031100346696810364910467495463786314015994459;
    uint256 constant IC0y = 21665662108092907012939155768322792633224282005821346326509651948634076562105;

    uint256 constant IC1x = 20122904746203086544722253239011365077358916002569359087600009736174578350948;
    uint256 constant IC1y = 11720564623596372151183314431949386794120088051426120890485455891704454740914;

    uint256 constant IC2x = 8773348486698517764254132517313842775668117525045467434193434983227470395916;
    uint256 constant IC2y = 20438565713591786749846371888830065511305649673116527426749666446439906089801;

    uint256 constant IC3x = 4167391981942117441815687069508274014224952079871343152113061612096178547286;
    uint256 constant IC3y = 11519800047052575260768304007527886437268227815009785876801901131414347464043;

    uint256 constant IC4x = 13080389862394297785339084088792533532608996946293563822287932849405288203291;
    uint256 constant IC4y = 21704322684554413570488138484364060521639498357038147841534512330583173180444;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 4 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
