// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_token_verifiers.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract. The confidential-token       #
// # circuits join the ceremony in the next cycle; until then #
// # this key is a development key by construction.           #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 confidential-token deposit-to-pool circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 14
contract Tidex6TokenDepositVerifier {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 15585012536757601693222637881570617644968318313375173210141545288548726025312;
    uint256 constant alphay = 12546036614804377878708713462240998677816142580597890855608465309189690244080;

    uint256 constant betax1 = 3459715188517196913664621056182970989293652722494660046287066805326494584177;
    uint256 constant betax2 = 10575497743397910323681659682586758135113741810553773658939301094539936309288;
    uint256 constant betay1 = 2551636233662038339813978380655366912656459076626709141580529640683692072204;
    uint256 constant betay2 = 9847680550756407421551844958506192652805379139000773906893544849663616211909;

    uint256 constant gammax1 = 9970672120202180152541979248227121059631430433060082795801967078790115457937;
    uint256 constant gammax2 = 15014316287858862804062540443468085623497498305256905509137194950221975851057;
    uint256 constant gammay1 = 18805423038408883452979208162181615097521252418551122791709431622548136525823;
    uint256 constant gammay2 = 18870936509090914421459330188820022947384466855476281721667119865294961901584;

    uint256 constant deltax1 = 844825431511132896238933146015420365912914947567141727131347992326660236133;
    uint256 constant deltax2 = 11973177913770460975593376190938024957494377941579348598727419375581720647103;
    uint256 constant deltay1 = 11024477061065275389767040917866374991096759239962453152993406878634373249221;
    uint256 constant deltay2 = 14079988633930062081016785270536790441297365929818919195463469395216489300112;

    uint256 constant IC0x = 20113278941419043012434709017204182846477097522204941346804588894559721452865;
    uint256 constant IC0y = 13468235935382222428367158299299482232475203180737005331904028065844975946186;

    uint256 constant IC1x = 12444186720684073485501635125400196781980570004001945446028770437296320017468;
    uint256 constant IC1y = 21263280519787739632859372484426415407635149359718698221259829389907255527185;

    uint256 constant IC2x = 21617735464793626801300505560227660477273632467829191325167449422049316120369;
    uint256 constant IC2y = 12163245092053322095356279492937378331657725018601372963465115868936697529123;

    uint256 constant IC3x = 16008177691684212570855823882602762480166680443867794400580344731820309196977;
    uint256 constant IC3y = 10802545083519084748870734138276178269842779271145490380907368166889868370945;

    uint256 constant IC4x = 1349044247782224739394388602886787645253993912644873171207197870811759204430;
    uint256 constant IC4y = 2732307661823573815957893772995541985614449983020760696612662181804549306766;

    uint256 constant IC5x = 1401731949019327546602795985587338270754633778925159424666693331429705769434;
    uint256 constant IC5y = 17643393921079936419767231927361182602235321270374758864495527851624319562788;

    uint256 constant IC6x = 3596857705879814125486248368591127607252129890017576932372136517800091100689;
    uint256 constant IC6y = 2599371293687107422551350416175269009719781952732100305576598055848416755115;

    uint256 constant IC7x = 91073962577427062687783949468198087110611115445761549609715275006092769542;
    uint256 constant IC7y = 7302344255317555820110221268953765853882948153421197345791158370793508980917;

    uint256 constant IC8x = 4866136932134887502064162762299736561208429364869089686030198863981299105255;
    uint256 constant IC8y = 3518367070820345058795424445517325604472590854123038686197451945667473105576;

    uint256 constant IC9x = 14482927276557069685640531013209850517368312784875009783297529586337155577182;
    uint256 constant IC9y = 10545634204045714911233111813616100777526975273711243081201180812677752553012;

    uint256 constant IC10x = 10649638415859076219240157939078599537938111777656576346998601279022236713632;
    uint256 constant IC10y = 2114149441241882726367132195555380570663906379908621586859086954248779353325;

    uint256 constant IC11x = 20915730504657886939289788512325716474349825608707670766676126683032719584551;
    uint256 constant IC11y = 17002638326648807243135241565609927036386814985287808328564699379649281919914;

    uint256 constant IC12x = 13911660468733200096504510334828504658121277067504956524613458345694574276924;
    uint256 constant IC12y = 19958072397747344601500376632024366882084734853461914678548872076050524489922;

    uint256 constant IC13x = 11350929611234383466707582505944551284493713960518138105063857764380198771188;
    uint256 constant IC13y = 16210358755004374541942063797929505983841669468482770577703869421211537989582;

    uint256 constant IC14x = 1423614923859857449831020258522612955572533560378457902499188163744805060684;
    uint256 constant IC14y = 2930231247799966033925408288199364377102877699611506933329356057111446422702;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 14 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[14] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1MulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                g1MulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                g1MulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                g1MulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))
                g1MulAccC(_pVk, IC9x, IC9y, calldataload(add(pubSignals, 256)))
                g1MulAccC(_pVk, IC10x, IC10y, calldataload(add(pubSignals, 288)))
                g1MulAccC(_pVk, IC11x, IC11y, calldataload(add(pubSignals, 320)))
                g1MulAccC(_pVk, IC12x, IC12y, calldataload(add(pubSignals, 352)))
                g1MulAccC(_pVk, IC13x, IC13y, calldataload(add(pubSignals, 384)))
                g1MulAccC(_pVk, IC14x, IC14y, calldataload(add(pubSignals, 416)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))
            checkField(calldataload(add(_pubSignals, 160)))
            checkField(calldataload(add(_pubSignals, 192)))
            checkField(calldataload(add(_pubSignals, 224)))
            checkField(calldataload(add(_pubSignals, 256)))
            checkField(calldataload(add(_pubSignals, 288)))
            checkField(calldataload(add(_pubSignals, 320)))
            checkField(calldataload(add(_pubSignals, 352)))
            checkField(calldataload(add(_pubSignals, 384)))
            checkField(calldataload(add(_pubSignals, 416)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
