// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_token_verifiers.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract. The confidential-token       #
// # circuits join the ceremony in the next cycle; until then #
// # this key is a development key by construction.           #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 confidential-token unwrap circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 7
contract Tidex6TokenUnwrapVerifier {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 9087660805993365583812844691920124290803186000926617680232968800340832652422;
    uint256 constant alphay = 4654660402553131630635328826203364533068498878761616982760075387262755523261;

    uint256 constant betax1 = 19707839014547110816201403720022211895091127823721671820574928712706354299670;
    uint256 constant betax2 = 8248293434455164707592117710318490365371605788957018726831183861046110362649;
    uint256 constant betay1 = 16181686898382747685173909824020981450033988671110310840781632868923369551502;
    uint256 constant betay2 = 18895165622217574605702685824602782707490048628623636242558413281159575097502;

    uint256 constant gammax1 = 7910681989832618084369936784627555807642940376448016698130745430688981269241;
    uint256 constant gammax2 = 140832980762377895083884384629066245277171230168553587001679049324642563113;
    uint256 constant gammay1 = 4363585083648586784844042192009728204859130549968059882140571501454136530126;
    uint256 constant gammay2 = 10018317160508586984547156903380102275488712370588307877876429699396211903408;

    uint256 constant deltax1 = 403617072387023655361843507964607612939666603186100923223431629845973048251;
    uint256 constant deltax2 = 3974330870946446471832727560073904317592321468049261577474698590250940501836;
    uint256 constant deltay1 = 5956363484561166036900824728210819936354731707934151300174001040859643998942;
    uint256 constant deltay2 = 9808706974132629742453668688292420449808492899447069489007834421779703519254;

    uint256 constant IC0x = 9196266214402340237162130889014121041088638155945391351011649233858785743123;
    uint256 constant IC0y = 15489203531255143700161626978284949004031726611527503543215456741610568244110;

    uint256 constant IC1x = 3515976633170010607522571476090719110907610641803682828563534409221514850758;
    uint256 constant IC1y = 6290354540414692247590606914993293017113698907089216402043926457207674390230;

    uint256 constant IC2x = 9982630849233726794312384343594377423166511962788532072482558484651628306286;
    uint256 constant IC2y = 13972256385271600623946829796828251159929958735924542707952179027216428751229;

    uint256 constant IC3x = 2373457574106302691332643477324520373536204542045608174806203230397835164639;
    uint256 constant IC3y = 15366125805260519026789716021830980543818888215668208624615878521347319637037;

    uint256 constant IC4x = 20077844700198433179908481879993978480073084225742975071209505736076471177151;
    uint256 constant IC4y = 19189840298217749508364541182470350414643501505950439802251037708557575870341;

    uint256 constant IC5x = 19292623714176614385152747684439530911634430043843628420662279798080624723011;
    uint256 constant IC5y = 12677115184206830536207776200780965969571567069622059430164875339422457044178;

    uint256 constant IC6x = 10310393068062886776585486608627783524861751856202671390922028924680007147556;
    uint256 constant IC6y = 4437853668989642125130782665574688536850213520458990534118749024150566162696;

    uint256 constant IC7x = 15811698093331134765158190052927711742242628166842363597518750965232618094321;
    uint256 constant IC7y = 6732598601207493538606269439936099499059234730411609341977092761438826616755;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 7 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[7] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1MulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                g1MulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                g1MulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))
            checkField(calldataload(add(_pubSignals, 160)))
            checkField(calldataload(add(_pubSignals, 192)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
