// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-circuits/src/bin/export_solidity_verifier.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract.                              #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 withdraw circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with `cargo run --bin export_solidity_verifier`.
/// @dev Public inputs: 5
contract Tidex6Verifier {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 15239853206260032156466557469938656564018514758704568384028784298619403196457;
    uint256 constant alphay = 20251732136298808494266843021789771367018273344106180963743229493673629075317;

    uint256 constant betax1 = 11439639946983917502648127932935994049998501780775180281229675088977254121175;
    uint256 constant betax2 = 21871473800312885271643815476476758858044382101548481487464671583160027471695;
    uint256 constant betay1 = 16787295154131657975443544446264331837460348520165648113125196783144085263219;
    uint256 constant betay2 = 6574303994832935575044400272075278154835866962386386452467372784349249584722;

    uint256 constant gammax1 = 12713653050615855490939780924235088887922870841477949250850514975003790632737;
    uint256 constant gammax2 = 8226105071428147249695749163841875843561115347187325308081329259474011775707;
    uint256 constant gammay1 = 11304852730508691342360034085483373536574199304993973654480928163800226256052;
    uint256 constant gammay2 = 6693763187015150114670441962571085102080358947253194426543640243079423399963;

    uint256 constant deltax1 = 20870280169434936236626832907158990117123778076773374399434651611109533995960;
    uint256 constant deltax2 = 8324716246141149492550819432774393817355719272398776021572026429327018199347;
    uint256 constant deltay1 = 6277043352826109508739488090321062736503854567968961956740360717560873267198;
    uint256 constant deltay2 = 16326662634189996715787206479271095245767166190403450351535612656888016501677;

    uint256 constant IC0x = 2526996261205236935150593887027670800843003814108087354598794583626449887466;
    uint256 constant IC0y = 1896273292572271647291268715684893751215962660354234714176841585202762143269;

    uint256 constant IC1x = 8813783125375908340943501127843996343559009422037805218303824643247000549312;
    uint256 constant IC1y = 1663962623343933587310413369931356139766626191343954248229068716346435153962;

    uint256 constant IC2x = 9557487845949950340283076413996769002572271375480159504660268436747060083337;
    uint256 constant IC2y = 14735727129352221255569850180726130685405548444907048936016331105512989861039;

    uint256 constant IC3x = 5019242873902237282807434613125405137678305165801412716091302733249713423698;
    uint256 constant IC3y = 12764558051827400155025891170424544593685685400079324792253877824331336881446;

    uint256 constant IC4x = 14145056637073675105726462563386645319773185916417410594092963856735822877469;
    uint256 constant IC4y = 8386707058232874773823126015780715104615246760193229257699626885068519160211;

    uint256 constant IC5x = 8011423421980130493179778853499792248911845460007239666417628518621078501439;
    uint256 constant IC5y = 2158171292170310606421866000289696311405392429506110344050019439298125545370;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 5 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[5] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1MulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
