// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_evm_verifiers_v2.rs`.
//
// ############################################################
// # DEVELOPMENT KEY (ADR-022 v2 circuits). Single-contributor  #
// # seeded setup: whoever knows the seed can forge proofs.     #
// # Testnet only until the v2 ceremony replaces it.            #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 v2 in-pool transfer circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 7
contract Tidex6HiddenTransferVerifierV2 {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 4808697264093380614237581441374203436340492467697779104581423693630519531040;
    uint256 constant alphay = 13122086782881967644908088867071410343103337131263235916262002975416745848950;

    uint256 constant betax1 = 19308977885314752507478274625840966891758292019330358653776502641102008170471;
    uint256 constant betax2 = 5824317401912765340345658270388772628346744674925403170642591565127945346010;
    uint256 constant betay1 = 20968472748039326967495927027578515202862190284842717388510903020628754199367;
    uint256 constant betay2 = 15919106988103754510015961013944626478733677094041890764645579391686260538453;

    uint256 constant gammax1 = 16276971376000536857662803378650112071091786112888857251561073283722146121616;
    uint256 constant gammax2 = 2949926545719371370262811064264889661209004163131649039486721151917465520014;
    uint256 constant gammay1 = 18551923628029725782921455793202293721564103897124067985373767439890100308745;
    uint256 constant gammay2 = 14937053776323861480249604668144171661335813367388485763752604658382614231056;

    uint256 constant deltax1 = 4495747594927898778442227276655736647201224670468616888575718235954974350417;
    uint256 constant deltax2 = 9059570223927367139494416384538479625374323071989123075519216653450873710776;
    uint256 constant deltay1 = 1845098025257639039990522288657801325320301502948251215121220040280685806986;
    uint256 constant deltay2 = 16760058295847682860301939156799171528088410112772883326768513872369004718125;

    uint256 constant IC0x = 7240975982427184974186070506386629482658691245678659439202401155021483132299;
    uint256 constant IC0y = 9408881244261543148238409199393920328215662692200195087635781461387177674721;

    uint256 constant IC1x = 7959465375008650337382676518305663231984436196511323488970049004350797372278;
    uint256 constant IC1y = 18348738148795960372404516019022179532520273203359119258683238372061929720645;

    uint256 constant IC2x = 5414379791747313453320522904907102499464337261616839565246373221398712586760;
    uint256 constant IC2y = 21783733349613129947314177638056809930499180078749026771117452624083277933194;

    uint256 constant IC3x = 6734176399236809616678878408754197730785976868914882793163763998283687323424;
    uint256 constant IC3y = 15841003487675619173545297725155814484230462837691976422061631685814294055415;

    uint256 constant IC4x = 5030908528456376679851899806924893401090927217646611488933480834001492971316;
    uint256 constant IC4y = 6315569065840324932156054724484599000551717635645841257595522403999719956057;

    uint256 constant IC5x = 2593359738748145516770903962320893436808976874445468717685704957758500989814;
    uint256 constant IC5y = 1860142220567211897347871263596413596803035662731197757489882953308786924227;

    uint256 constant IC6x = 5382398265221076556149580659845116970413925374577756169324171384105113169702;
    uint256 constant IC6y = 20468522001202460298754732947543960059954047727273125749889908315435009167774;

    uint256 constant IC7x = 16749499873273300292804891699799804030020683866715007884172576552329148073844;
    uint256 constant IC7y = 12847970928931829585959304842646717286995495243390831927085965683608354988306;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 7 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[7] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1MulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                g1MulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                g1MulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))
            checkField(calldataload(add(_pubSignals, 160)))
            checkField(calldataload(add(_pubSignals, 192)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
