// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_evm_verifiers_v2.rs`.
//
// ############################################################
// # DEVELOPMENT KEY (ADR-022 v2 circuits). Single-contributor  #
// # seeded setup: whoever knows the seed can forge proofs.     #
// # Testnet only until the v2 ceremony replaces it.            #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 v2 withdraw circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 8
contract Tidex6HiddenWithdrawVerifierV2 {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 10593780476796523958584485928314846971286900445167545496456664158649591711495;
    uint256 constant alphay = 7155599427818153737080918216021093541158786618417655731701147269203244416786;

    uint256 constant betax1 = 217730027938559133573532727340487005115090684113377628475897429969627983294;
    uint256 constant betax2 = 9404632652605250451191877268854016952166912505856711608612049697848741958972;
    uint256 constant betay1 = 18724123591001220573725326137044467317980920075782196750044319279845955051141;
    uint256 constant betay2 = 6349586362753925180382801627009305016087656994335997902011716541388901253614;

    uint256 constant gammax1 = 10092056243368924343474328215823563645827266739996529537327523233466486835123;
    uint256 constant gammax2 = 12652665179984533544798032890739119843328376601178674786964672332736508917397;
    uint256 constant gammay1 = 11058515589752847232433874607691217454288217250742681829703436086077069776620;
    uint256 constant gammay2 = 6081776667966090120946639919501718864390537199831745064513820472150128241991;

    uint256 constant deltax1 = 11203115217007353471165443671818449467515887976730281959287578714816866496364;
    uint256 constant deltax2 = 257440816142272841846252123541433911871132562915080787901841724551329586460;
    uint256 constant deltay1 = 21856132505177169397631674783259735822259833971906582470696214514896449338722;
    uint256 constant deltay2 = 12368806118868485845106872833420728406074110494764823844836905212214387612298;

    uint256 constant IC0x = 17750445443663805938274127999549331362464111363400938101728139501401800428071;
    uint256 constant IC0y = 3593034247442956401224127108341543275707505285713641409650469570835135759771;

    uint256 constant IC1x = 11734677228277063516466331559229461821562879550317329848310371957499790127179;
    uint256 constant IC1y = 3497483193986944425813374826705819052758054356812321473371371126426439068062;

    uint256 constant IC2x = 3449456994795344741987699369893777548121875293141176023407258255729356541937;
    uint256 constant IC2y = 2563141390604249226516882946578635851169934118396756343123766137335593824517;

    uint256 constant IC3x = 2237274742587999491161461295192678809184389268919048947399914685707648217765;
    uint256 constant IC3y = 15879184883632635267368593623672376168989400057199503850415783388571453285810;

    uint256 constant IC4x = 12969846108420668754301139872869950353291770221291961151029210977526735325103;
    uint256 constant IC4y = 17752225029835053562596269068556460559903194360051395101518523043314894467037;

    uint256 constant IC5x = 4783896228041245950327563528596286181321897013419523451833927784933867768190;
    uint256 constant IC5y = 10416399598917510630353207849319944200394802120629263499555520674624197850805;

    uint256 constant IC6x = 4864043330975986697827522128746703828154888375090274982839176812269908861650;
    uint256 constant IC6y = 21181316544289842263366605514041186999915545797405391545367174915615471982388;

    uint256 constant IC7x = 6491481315249776825361272665855938822547658576984769657856071743764646095927;
    uint256 constant IC7y = 2657166929328862076909190234600734446409697013281954398162020919913139346996;

    uint256 constant IC8x = 4674562447992605684115787210339168894158787310815673273536673167274413535723;
    uint256 constant IC8y = 11285791426262626038029604587308282968797326847061853860096394271250663531315;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 8 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[8] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1MulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                g1MulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                g1MulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                g1MulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))
            checkField(calldataload(add(_pubSignals, 160)))
            checkField(calldataload(add(_pubSignals, 192)))
            checkField(calldataload(add(_pubSignals, 224)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
