// DO NOT EDIT BY HAND. Generated by
// `crates/tidex6-confidential/src/bin/export_token_verifiers.rs`.
//
// ############################################################
// # DEVELOPMENT KEY — NOT FROM THE PUBLIC CEREMONY.          #
// # Derived from a seed in the public repository, so anyone  #
// # can forge proofs against it. Testnet only. Do not put    #
// # value behind this contract. The confidential-token       #
// # circuits join the ceremony in the next cycle; until then #
// # this key is a development key by construction.           #
// ############################################################

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/// @title Groth16 verifier for the tidex6 confidential-token pool-exit circuit
/// @notice Verifies BN254 Groth16 proofs produced by the tidex6 browser
///         prover. Generated from the verifying key — do not edit by hand;
///         regenerate with the exporter named in the header.
/// @dev Public inputs: 8
contract Tidex6TokenExitVerifier {
    // Base field modulus.
    uint256 constant q =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;
    // Scalar field modulus.
    uint256 constant r =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    // Verifying key.
    uint256 constant alphax = 5095582951474687414119123090878156865494402481460739546117810360694064203043;
    uint256 constant alphay = 469422681786304034376190145338036761007756268749054407323429219898082443124;

    uint256 constant betax1 = 18056247383846608653148129030904924696255680778469416239335775022664384424431;
    uint256 constant betax2 = 19599231669303989151930262407551654206467987869266428506617275998493986681599;
    uint256 constant betay1 = 12433262011316897327053153598028173938277528084745909134224540770360201029834;
    uint256 constant betay2 = 8353561027516770274663463586834617178360085535215425006533769000633958192642;

    uint256 constant gammax1 = 21641593732980130231403202281439760455750402421927659742003422234234971335924;
    uint256 constant gammax2 = 149372406554726745220572874598723239834750308269025023075155358504887748200;
    uint256 constant gammay1 = 18592765543157743457116899570134232318113935975488658366433463773051436366869;
    uint256 constant gammay2 = 14336184702008995342311938957634960250538386438017190200246379906393752544;

    uint256 constant deltax1 = 15471825669049730506194693426977761974182553416152122202332003692014502153712;
    uint256 constant deltax2 = 16454036382208124863777898505770524981350075113112422310870185018754073167424;
    uint256 constant deltay1 = 20724739890489960831304006450343471002219498591987283512059008153799900406613;
    uint256 constant deltay2 = 8558640618986777019779359299041973226324958646663377345404113968667584112220;

    uint256 constant IC0x = 12231540985686914654620894356621881335588181901250129439847152434287770290692;
    uint256 constant IC0y = 13418078483688315672982717277710257125905692066983626343741623725044833533652;

    uint256 constant IC1x = 8336448575841269785614972377345486688276917569607548457747943856235241990219;
    uint256 constant IC1y = 3505576605858004674229636299088342693714118446090571930931100836299628768287;

    uint256 constant IC2x = 11651280961667643609904074897415602955685202963511053650928185831055225897781;
    uint256 constant IC2y = 10622865731122453703329383273619899099950987968823450188436732591350407098791;

    uint256 constant IC3x = 3596689691394706862988052142635246115428793486565459907234735288392528298301;
    uint256 constant IC3y = 11575969516992970904174970771571957728544366076831597015080546134659410317268;

    uint256 constant IC4x = 10334960442491722421366254431764683819575010134478680060977964898324532370928;
    uint256 constant IC4y = 18686927352393746311509125609182116835856177707647332466246322283795355967824;

    uint256 constant IC5x = 13514235928085565744860554360962107918985082818796573169957520696779329806078;
    uint256 constant IC5y = 9422806727455833392048454221402474449185654945999605254622491978738830499451;

    uint256 constant IC6x = 11972429517593530341042722400957328795582357126641665442613686216328280458995;
    uint256 constant IC6y = 1938231684762141676825501511211445295541604645750526059202394423388287967890;

    uint256 constant IC7x = 715439859084340939662703135285789346370654057862527480612931715822676585468;
    uint256 constant IC7y = 5676934139756647515142141748583312437785328869236820348613891194156064892571;

    uint256 constant IC8x = 19529234136731876538247345266002145276769455848271938055042840014924395721689;
    uint256 constant IC8y = 7999436219470261484182848987280480553165895171373891076824507663077719203453;

    uint16 constant pVk = 0;
    uint16 constant pPairing = 128;

    uint16 constant lastMem = 896;

    /// @notice Verify a Groth16 proof.
    /// @param _pA Proof element A.
    /// @param _pB Proof element B, in EVM pairing order.
    /// @param _pC Proof element C.
    /// @param _pubSignals The 8 public inputs.
    /// @return True when the proof is valid for these inputs.
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[8] calldata _pubSignals
    ) public view returns (bool) {
        assembly {
            function checkField(v) {
                if iszero(lt(v, r)) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            // G1 scalar multiply-accumulate into the memory at `pR`.
            function g1MulAccC(pR, x, y, s) {
                let success
                let mIn := mload(0x40)
                mstore(mIn, x)
                mstore(add(mIn, 32), y)
                mstore(add(mIn, 64), s)

                success := staticcall(sub(gas(), 2000), 7, mIn, 96, mIn, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }

                mstore(add(mIn, 64), mload(pR))
                mstore(add(mIn, 96), mload(add(pR, 32)))

                success := staticcall(sub(gas(), 2000), 6, mIn, 128, pR, 64)
                if iszero(success) {
                    mstore(0, 0)
                    return(0, 0x20)
                }
            }

            function checkPairing(pA, pB, pC, pubSignals, pMem) -> isOk {
                let _pPairing := add(pMem, pPairing)
                let _pVk := add(pMem, pVk)

                mstore(_pVk, IC0x)
                mstore(add(_pVk, 32), IC0y)

                // Accumulate the public-input commitment.
                g1MulAccC(_pVk, IC1x, IC1y, calldataload(add(pubSignals, 0)))
                g1MulAccC(_pVk, IC2x, IC2y, calldataload(add(pubSignals, 32)))
                g1MulAccC(_pVk, IC3x, IC3y, calldataload(add(pubSignals, 64)))
                g1MulAccC(_pVk, IC4x, IC4y, calldataload(add(pubSignals, 96)))
                g1MulAccC(_pVk, IC5x, IC5y, calldataload(add(pubSignals, 128)))
                g1MulAccC(_pVk, IC6x, IC6y, calldataload(add(pubSignals, 160)))
                g1MulAccC(_pVk, IC7x, IC7y, calldataload(add(pubSignals, 192)))
                g1MulAccC(_pVk, IC8x, IC8y, calldataload(add(pubSignals, 224)))

                // -A
                mstore(_pPairing, calldataload(pA))
                mstore(
                    add(_pPairing, 32),
                    mod(sub(q, calldataload(add(pA, 32))), q)
                )

                // B
                mstore(add(_pPairing, 64), calldataload(pB))
                mstore(add(_pPairing, 96), calldataload(add(pB, 32)))
                mstore(add(_pPairing, 128), calldataload(add(pB, 64)))
                mstore(add(_pPairing, 160), calldataload(add(pB, 96)))

                // alpha1
                mstore(add(_pPairing, 192), alphax)
                mstore(add(_pPairing, 224), alphay)

                // beta2
                mstore(add(_pPairing, 256), betax1)
                mstore(add(_pPairing, 288), betax2)
                mstore(add(_pPairing, 320), betay1)
                mstore(add(_pPairing, 352), betay2)

                // vk_x
                mstore(add(_pPairing, 384), mload(_pVk))
                mstore(add(_pPairing, 416), mload(add(_pVk, 32)))

                // gamma2
                mstore(add(_pPairing, 448), gammax1)
                mstore(add(_pPairing, 480), gammax2)
                mstore(add(_pPairing, 512), gammay1)
                mstore(add(_pPairing, 544), gammay2)

                // C
                mstore(add(_pPairing, 576), calldataload(pC))
                mstore(add(_pPairing, 608), calldataload(add(pC, 32)))

                // delta2
                mstore(add(_pPairing, 640), deltax1)
                mstore(add(_pPairing, 672), deltax2)
                mstore(add(_pPairing, 704), deltay1)
                mstore(add(_pPairing, 736), deltay2)

                let success := staticcall(
                    sub(gas(), 2000),
                    8,
                    _pPairing,
                    768,
                    _pPairing,
                    0x20
                )

                isOk := and(success, mload(_pPairing))
            }

            let pMem := mload(0x40)
            mstore(0x40, add(pMem, lastMem))

            // Reject public inputs outside the scalar field.
            checkField(calldataload(add(_pubSignals, 0)))
            checkField(calldataload(add(_pubSignals, 32)))
            checkField(calldataload(add(_pubSignals, 64)))
            checkField(calldataload(add(_pubSignals, 96)))
            checkField(calldataload(add(_pubSignals, 128)))
            checkField(calldataload(add(_pubSignals, 160)))
            checkField(calldataload(add(_pubSignals, 192)))
            checkField(calldataload(add(_pubSignals, 224)))

            let isValid := checkPairing(_pA, _pB, _pC, _pubSignals, pMem)

            mstore(0, isValid)
            return(0, 0x20)
        }
    }
}
